"""initial migration

Revision ID: 089a634c595a
Revises: 201ec80518b7
Create Date: 2025-04-21 15:04:16.210268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089a634c595a'
down_revision = '201ec80518b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transfers_completed_by_users'), 'users', ['completed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transfers_completed_by_users'), type_='foreignkey')
        batch_op.drop_column('completed_by')

    # ### end Alembic commands ###
