"""added transfer tables

Revision ID: 1fd2462e0e20
Revises: 64bb97b94e72
Create Date: 2025-04-16 20:02:58.716619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd2462e0e20'
down_revision = '64bb97b94e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_dob', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('patient_phone_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('medication_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('dosage', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('quantity_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refills_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prescribing_doctor', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('doctor_contact', sa.String(length=100), nullable=True))
        batch_op.alter_column('prescription_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.alter_column('prescription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('doctor_contact')
        batch_op.drop_column('prescribing_doctor')
        batch_op.drop_column('refills_remaining')
        batch_op.drop_column('quantity_remaining')
        batch_op.drop_column('dosage')
        batch_op.drop_column('medication_name')
        batch_op.drop_column('patient_phone_number')
        batch_op.drop_column('patient_dob')
        batch_op.drop_column('patient_last_name')
        batch_op.drop_column('patient_first_name')

    # ### end Alembic commands ###
