"""initial migration

Revision ID: 201ec80518b7
Revises: 1fd2462e0e20
Create Date: 2025-04-18 18:39:54.124709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201ec80518b7'
down_revision = '1fd2462e0e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('prescribing_doctor')
        batch_op.drop_column('quantity_remaining')
        batch_op.drop_column('dosage')
        batch_op.drop_column('refills_remaining')
        batch_op.drop_column('doctor_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_contact', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('refills_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dosage', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('quantity_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('prescribing_doctor', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
