"""initial migration

Revision ID: 3143902278bc
Revises: 71d9932afee0
Create Date: 2025-04-15 22:39:55.352190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3143902278bc'
down_revision = '71d9932afee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patients_pharmacies_patient_id_patients')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_patients_pharmacies_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patients_pharmacy_id_pharmacies', type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_patients_pharmacy_id_pharmacies', 'pharmacies', ['pharmacy_id'], ['id'])

    op.drop_table('patients_pharmacies')
    # ### end Alembic commands ###
