"""Add fields to Prescription

Revision ID: 45d4aa917005
Revises: a3d42b306e15
Create Date: 2025-04-26 21:35:15.502005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d4aa917005'
down_revision = 'a3d42b306e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directions_for_use', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_of_prescription', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_last_filled', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('prescriber_full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('prescriber_dea_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prescriber_contact_info', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('prescriber_contact_info')
        batch_op.drop_column('prescriber_dea_number')
        batch_op.drop_column('prescriber_full_name')
        batch_op.drop_column('date_last_filled')
        batch_op.drop_column('date_of_prescription')
        batch_op.drop_column('refills')
        batch_op.drop_column('directions_for_use')

    # ### end Alembic commands ###
