"""transfer to postgress

Revision ID: 48b33cf952d9
Revises: 
Create Date: 2025-04-29 10:45:58.947808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48b33cf952d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_pharmacy_patients_patient_id_patients')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_pharmacy_patients_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('directions_for_use', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('refills', sa.Integer(), nullable=True),
    sa.Column('date_of_prescription', sa.Date(), nullable=True),
    sa.Column('date_last_filled', sa.Date(), nullable=True),
    sa.Column('prescriber_full_name', sa.String(length=200), nullable=True),
    sa.Column('prescriber_dea_number', sa.String(length=50), nullable=True),
    sa.Column('prescriber_contact_info', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'PHARMACIST', 'TECHNICIAN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_users_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pharmacy_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_pharmacy_prescriptions_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_pharmacy_prescriptions_prescription_id_prescriptions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('from_pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('to_pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('patient_first_name', sa.String(length=100), nullable=False),
    sa.Column('patient_last_name', sa.String(length=100), nullable=False),
    sa.Column('patient_dob', sa.Date(), nullable=False),
    sa.Column('patient_phone_number', sa.String(length=200), nullable=True),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('transfer_status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='transfer_status'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_transfers_completed_by_users')),
    sa.ForeignKeyConstraint(['from_pharmacy_id'], ['pharmacies.id'], name=op.f('fk_transfers_from_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_transfers_prescription_id_prescriptions')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_transfers_requested_by_users')),
    sa.ForeignKeyConstraint(['to_pharmacy_id'], ['pharmacies.id'], name=op.f('fk_transfers_to_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('pharmacy_prescriptions')
    op.drop_table('users')
    op.drop_table('prescriptions')
    op.drop_table('pharmacy_patients')
    op.drop_table('pharmacies')
    op.drop_table('patients')
    # ### end Alembic commands ###
