"""initial migration

Revision ID: 591464b8de02
Revises: e5dbf81c8bc3
Create Date: 2025-04-15 17:13:02.697833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591464b8de02'
down_revision = 'e5dbf81c8bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
