"""added transfer tables

Revision ID: 64bb97b94e72
Revises: 1521cea9b195
Create Date: 2025-04-16 16:00:23.444089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64bb97b94e72'
down_revision = '1521cea9b195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('from_pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('to_pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('transfer_status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANDELLED', name='transfer_status'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_pharmacy_id'], ['pharmacies.id'], name=op.f('fk_transfers_from_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_transfers_prescription_id_prescriptions')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_transfers_requested_by_users')),
    sa.ForeignKeyConstraint(['to_pharmacy_id'], ['pharmacies.id'], name=op.f('fk_transfers_to_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    # ### end Alembic commands ###
