"""update

Revision ID: a3d42b306e15
Revises: 089a634c595a
Create Date: 2025-04-23 12:01:34.621393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3d42b306e15'
down_revision = '089a634c595a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_pharmacy_patients_patient_id_patients')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_pharmacy_patients_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.ENUM('ADMIN', 'PHARMACIST', 'TECHNICIAN', name='user_role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'PHARMACIST', 'TECHNICIAN', name='user_role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('pharmacy_patients')
    # ### end Alembic commands ###
