"""initial migration

Revision ID: b5de65abb3b1
Revises: a702e475df22
Create Date: 2025-04-15 18:08:09.594407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5de65abb3b1'
down_revision = 'a702e475df22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('ADMIN', 'OWNER', 'PHARMACY_MANAGER', 'OPERATIONS_MANAGER', 'HR_MANAGER', 'PHARMACIST_IN_CHARGE', 'PHARMACIST', 'STAFF_PHARMACIST', 'INTERN_PHARMACIST', 'PHARMACY_TECHNICIAN', name='user_role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'OWNER', 'PHARMACY_MANAGER', 'OPERATIONS_MANAGER', 'HR_MANAGER', 'PHARMACIST_IN_CHARGE', 'PHARMACIST', 'STAFF_PHARMACIST', 'INTERN_PHARMACIST', 'PHARMACY_TECHNICIAN', name='user_role'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
